### Create a new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
   "email": "asdf@asdf.com",
   "password": "12345"
}

### Sign In a User

POST http://localhost:3000/auth/signin
content-type: application/json

{
   "email": "asdf@asdf.com",
   "password": "12345"
}

### Get a currently signed in user
GET http://localhost:3000/auth/whoami

### Signout a logged in user

POST http://localhost:3000/auth/signout

### Find a particular user with a given email id
GET http://localhost:3000/auth?test@test.com

### Delete a user with given user id
DELETE  http://localhost:3000/auth/8

### Delete a user with the email
DELETE http://localhost:3000/auth/withEmail/test@test.com	

### Update a user with given data
PATCH http://localhost:3000/auth/2
content-type: application/json

{
   "email": "asdf@asdf.com",
   "admin": true
}

### Set a color
GET http://localhost:3000/auth/colors/red

### Get a color
GET http://localhost:3000/auth/colors